name: Safemoney CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        runner: [ip-10-0-0-213, safemoney-cd]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull onathandavid/safemoney:java

      - name: Stop Docker container
        run: docker stop java-safemoney || true

      - name: Remove Docker container
        run: docker rm java-safemoney || true

      - name: Run Docker container
        run: docker run --name java-safemoney -d -p 8080:8080 onathandavid/safemoney:java