name: Safemoney CD

on:
    pull_request:
        branches:
          - main
        types: [opened, reopened]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Pull Docker image
              run: docker pull onathandavid/safemoney:java

            - name: Stop Docker container
              run: docker stop ci-example || true

            - name: Remove Docker container
              run: docker rm ci-example || true

            - name: Run Docker container
              run: docker run --name ci-example -d -p 8080:8080 onathandavid/safemoney:java
              